### ISSUE TITLE
First Investment Not Added to Vehicle

### ISSUE THREAD

**Issue by FaceFTW** [RetireSimple/RetireSimple#181]
**Describe the bug**
Assuming a fresh launch, there is an issue with having the first investment created to be added in an investment vehicle, it requires another investment to properly indicate it has been placed in that vehicle.

**To Reproduce**
@kimtracy Please add steps

**Expected behavior**

**Screenshots**
N/A

**Desktop (please complete the following information):**

**Additional context**
Documented by @kimtracy

**Comment by kimtracy** [comment]
I'm not 100% sure of these steps, but I recall them being:
- entered an investment (a stock) which properly appeared in just the investments
- created a vehicle
- added a bond investment to the vehicle
- noticed that the bond investment didn't appear in the vehicle, but under the investments
- added another investment (stock) to the same vehicle
- noticed that the bond investment now appeared under the vehicle
I don't recall ever trying to refresh the screen at any point.

**Comment by kimtracy** [comment]
I do see an error in the log which might be related: unhandled exception - "The specified investment has no specified investments" BondInvestment.cs: line 73.  I see that error several times in the log-- may be what was causing bonds to not "get data"

**Comment by FaceFTW** [comment]
I can't seem to reproduce this bug. I am working with a clean database and will try variations to see if I can find any similar behavior.

The error you mentioned indicates that the type of Bond Analysis set is not valid when trying to trigger analysis (in this case we only have one valid option for Bonds). I have theories on how it happens, it may need to be done in a separate issue.

**Comment by FaceFTW** [comment]
Issue still present after patch release, reopening, steps to reproduce are same/similar. Suspected reasons after demonstration is a double load occurring when it shouldn't, thus causing frontend state to be desynchronized.
