### ISSUE TITLE
Bond Analysis view in Frontend Does Not Trigger

### ISSUE THREAD

**Issue by FaceFTW** [RetireSimple/RetireSimple#183]
**Describe the bug**
Similar to #182, but for the bond analysis view

**To Reproduce**
@kimtracy please add steps

**Expected behavior**
The bond analysis view should show after clicking the "Get Data" button

**Screenshots**
N/A

**Desktop (please complete the following information):**
 N/A

**Additional context**
Documented by @kimtracy

**Comment by kimtracy** [comment]
Noted in Issue 181.
Also, this appears to be related:
I do see an error in the log which might be related: unhandled exception - "The specified investment has no specified investments" BondInvestment.cs: line 73. I see that error several times in the log-- may be what was causing bonds to not "get data"
