### ISSUE TITLE
[Engine] Reflection for Analysis Delegate Resolution

### ISSUE THREAD

**Issue by FaceFTW** [RetireSimple/RetireSimple#51]

**Comment by rhit-westeraj** [comment]
This issue is low-prority, but may be pursued if deemed relevant

**Comment by FaceFTW** [comment]
Potential Solution, should be investigated as it would influence documentation.

We could use a custom attribute, give it two properties (an "internal name" and the class name of the investment type), then find all methods with that attribute and matching investment type, then try to resolve that internal name. Couple of issues given how we currently implement analysis delegates

- A significant number of unit tests could break if we mandate using this method (not to mention it makes a significant number of things , so we would keep the old method as a "legacy" or "test-only" constructor. We can definitely discourage access through the use of access modifiers or the `Obsolete` attribute
- Reflection performance is an issue if we have to find the list on each construction. Possibly, we can have the API layer on construction to do the reflection before hand (thus requiring reflection to occur at least once per API construction), then "cache the results" in a type of map associating investment types with each resolved delegate.
- This could put more on the developer because they have to implement a specific constructor. In theory, leveraging inheritance and having the `InvestmentBase` provide a common constructor could be a viable solution, and thus remove that responsibility from the developer. This could work because (***in theory***) we can simply use the class name of the constructed type, which should be the specific extending type and not `InvestmentBase`
- There would be a significant amount of testing required, and no clean way (from my current understanding) of doing it

Some thoughts, this does not indicate commitment.
